#! /bin/bash

bootstrap=$(realpath "${BASH_SOURCE[0]}")
bootstrap_directory=$(dirname "${bootstrap}")
rootdir=$(realpath "${bootstrap_directory}/../..")

TEMPLATECONF="${rootdir}/layers/meta-navigator/conf/templates/default" \
    source "${rootdir}/layers/core/oe-init-build-env"
